name: biometric_pay
description: GPay-like biometric payment demo
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.2.0

flutter:
  uses-material-design: true